# Visualiseren van elektrische velden rondom één of meerdere ladingen

## 1. De elektrische veldsterkte $\vec{E}$

### 1.1. $\vec{E}$ beschrijven op een r-as

In een punt P op een afstand _r_ van een elektrische lading _Q_ wordt de elektrische veldsterkte beschreven door
$$
\vec{E} = k \, \frac{Q}{r^2} \, \vec{e_r}
$$
met $k = 8,99 \times 10^9 \frac{N m^2}{C^2}$ de Coulombconstante en $\vec{e_r}$ de eenheidsvector in de
radiale richting weg van de lading _Q_ zoals op onderstaande figuur. Merk op, de figuur is enkel correct voor een lading _Q_>0 C.

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_E-ras.png?raw=true' width='50%'>

In bovenstaand assenstelsel kunnen we dus de vector $\vec{E}$ schrijven als een aantal keer de eenheidsvector $\vec{e_r}$:
$$
\boxed{\vec{E} = E_r \, \vec{e_r} \quad {\rm met \ als \ component} \quad E_r = k \, \frac{Q}{r^2}}
$$

Met bovenstaande formule vinden we dat de elektrische veldsterkte $\vec{E}$ in het punt P dezelfde richting en zin heeft als de eenheidsvector (weg van de lading _Q_) als _Q_>0 C. Daarentegen, was _Q_<0 C, dan zou de zin van de elektrische veldsterkte in het punt P tegengesteld zijn aan de zin van de eenheidsvector.

Deze theoretische beschrijving van de elektrische veldsterkte komt overeen met de formule hoe je die in de lessen fysica hebt gedefinieerd. En wees jouw leraar fysica maar dankbaar, want dat was een zeer bewuste keuze. Hoewel je niet gewoon bent om met een _r-as_ te werken, maakt het de fysische formules heel eenvoudig.

<span style="color:#1569C7">**Opdracht 1.**</span>  Schrijf een eigen functie met de naam `Ercomponent(q,r)` met _q_ de bronlading en _r_ de afstand van de bronlading tot het punt P. Als retourwaarde geeft de functie de r-component $E_r$.

**Voorbeeld:**
Bij het uitvoeren van jouw functie met argumenten 1 nC en 1 m:
```python
# maak hier jouw functie Ercomponent() aan
print( 'E_r =', Ercomponent(1e-9,1), 'N/C')
```
is de uitvoer:
```
E_r = 8.99 N/C
```

In [1]:
# maak hier jouw functie Ercomponent() aan
def Ercomponent(q,r):
    k = 8.99*10**9 # Nm²/C²
    E_r = k*q/(r**2)
    return E_r

print( 'E_r =', Ercomponent(1*10**(-9),1), 'N/C')
# *10**(-9) is hetzelfde als e-9

E_r = 8.99 N/C


<span style="color:#1569C7">**Opdracht 2.**</span> We breiden vorige opdracht een klein beetje uit door de oorsprong van de r-as niet op de bronlading te kiezen. Dit kunnen we doen door de functie `Ercomponent(q,r0,r)` drie argumenten te geven. _q_ is nog steeds de bronlading, _r0_ is de afstand van de oorsprong tot de bronlading en _r_ is de afstand van de oorsprong tot het punt P. De retourwaarde van jouw functie is opnieuw de r-component $E_r$.

> TIP: Zorg dat jouw functie voldoende commentaarlijnen bevat om duidelijk leesbaar te zijn!

**Voorbeeld:**
Bij het uitvoeren van jouw functie met argumenten 1 nC, 0.5 m en 1.0 m:
```python
# maak hier jouw functie Ercomponent() aan
print( 'E_r =', Ercomponent(1e-9,0.5,1.0), 'N/C')
```
is de uitvoer:
```
E_r = 35.96 N/C
```

### 1.2. $\vec{E}$ beschrijven op een x- en y-as

Hoewel de beschrijving van de elektrische veldsterktevector zonder twijfel best gebeurt op een r-as, maken we de theorie even wat moeilijker (stel je voorlopig nog niet de vraag _waarom_) door de elektrische veldsterkte vector voor te stellen in een xy assenstelsel in plaats van op een enkele r-as:

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_E-xyas.png?raw=true' width='50%'>
<!-- VERVANG DOOR PDF, MAAR HOE IMPORTEREN? -->

Het gevolg is dat - door onze moeilijke keuze van assenstelsel - we in dit xy assenstelsel de vector <span style="color:blue">$\vec{E}$</span> niet kunnen beschrijven met een $E_r$ component, we hebben daarentegen twee componenten nodig: <span style="color:red">$E_x$</span> volgens de $\vec{e_x}$ richting en <span style="color:red">$E_y$</span> volgens de $\vec{e_y}$ richting. Zo wordt:
$$
\vec{E} = E_x \vec{e_x} + E_y \vec{e_y}
$$

We moeten dus op zoek naar de componenten $E_x$ en $E_y$. We gebruiken hiervoor de gele en grijze rechthoekige driehoeken in bovenstaande figuur:

- In de gele driehoek passen we de stelling van Pythagoras toe. De afstand $r$ tussen de lading $Q$ en het punt P in termen van $x$ en $y$ wordt zo:
$$ r^2 = x^2 + y^2 \quad {\rm dus} \quad r = \sqrt{x^2 + y^2}. $$

- In de grijze driehoek passen we de goniometrische relatie voor sinus en cosinus van de hoek $\theta$ toe:
$$ \cos{\theta} = \frac{E_x}{E_r} \quad {\rm en} \quad \sin{\theta} = \frac{E_y}{E_r} $$

Met de laatste gelijkheden vinden we achtereenvolgens een uitdrukking voor de componenten $E_x$ en $E_y$:
$$
\begin{align}
E_x &= E_r \cdot \cos{\theta} \\
    &= k \frac{Q}{r^2} \cdot \frac{x}{r} \\
    &= k \, Q \frac{x}{r^3} \\
    &= k \, Q \frac{x}{(x^2+y^2)^{3/2}} \\ \\
E_y &= E_r \cdot \sin{\theta} \\
    &= k \frac{Q}{r^2} \cdot \frac{y}{r} \\
    &= k \, Q \frac{y}{r^3} \\
    &= k \, Q \frac{y}{(x^2+y^2)^{3/2}}
\end{align}
$$

Samengevat: als we de elektrische veldsterkte $\vec{E}$ willen voorstellen in een xy assenstelsel, dan geldt:
$$
\boxed{\vec{E} = E_x \vec{e_x} + E_y \vec{e_y} \quad {\rm met \ als \ componenten} \quad
\begin{cases}
    E_x & = k \, Q \frac{x}{(x^2+y^2)^{3/2}} \\
    E_y & = k \, Q \frac{y}{(x^2+y^2)^{3/2}}
\end{cases}
}
$$

<span style="color:#1569C7">**Opdracht 3.**</span> Schrijf een nieuwe functie met de naam `Exycomponenten(q,x,y)` met _q_ de bronlading en _x_ en _y_ de componenten van het punt P als we de oorsprong van het xy assenstelsel gelijkstellen met de bronlading. Als retourwaarde geeft de functie de x- en y-componenten $E_x$ en $E_y$.

**Voorbeeld:**
Bij het uitvoeren van jouw functie met argumenten 2.6 nC, 3.0 m en 2.0 m:
```python
# maak hier jouw functie Exycomponenten() aan
print( 'E_x,E_y =', Exycomponenten(2.6e-9,3.0,2.0), 'N/C')
```
is de uitvoer:
```
E_x,E_y = (1.496026429219443, 0.997350952812962) N/C
```

<span style="color:#1569C7">**Opdracht 4.**</span> We breiden opnieuw de vorige opdracht een klein beetje uit door de oorsprong van het xy assenstelsel niet op de bronlading te kiezen. Schrijf de functie `Exycomponenten(q,xQ,yQ,xP,yP)` die vijf argumenten aanvaardt: _q_ is de bronlading, _xQ_ en _yQ_ zijn de x- en y-coordinaten van de bronlading, terwijl _xP_ en _yP_ de coordinaten zijn van het punt P waar we de veldsterkte willen bepalen. De retourwaarde van jouw functie is opnieuw de twee componenten $E_x$ en $E_y$.

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_E-xyas-nietoorspront.png?raw=true' width='50%'>

> TIP: Neem $x = x_P - x_Q$ en $y = y_P - y_Q$ zodat we nog steeds kunnen gebruiken dat
> $$
  \begin{cases}
     E_x & = k \, Q \frac{x}{(x^2+y^2)^{3/2}} \\
     E_y & = k \, Q \frac{y}{(x^2+y^2)^{3/2}}
  \end{cases}
  $$

**Voorbeeld:**
Bij het uitvoeren van jouw functie met argumenten 2.1 nC, 1.0 m, 1.5 m, 4.0 m en 3.0 m:
```python
# maak hier jouw functie Exycomponenten() aan
print( 'E_x,E_y =', Exycomponenten(2.1e-9,1.0,1.5,4.0,3.0), 'N/C')
```
is de uitvoer:
```
E_x,E_y = (1.5009680834566588, 0.7504840417283294) N/C
```

## 2. Voorstelling van de ladingen

### 2.1. Locatie(s) van één of meerdere puntladingen

In dit tweede deel van het project gaan we puntladingen plaatsen binnen het xy assenstelsel. Daarvoor moeten we over elke puntlading drie gegevens specifiëren:
- de lading _q_ die zowel positief als negatief kan zijn;
- de x-coordinaat van de puntlading binnen het xy assenstelsel;
- de y-coordinaat van de puntlading binnen het xy assenstelsel.

<span style="color:#1569C7">**Opdracht 5.**</span> Schijf een functie `puntlading()` die geen argumenten aanvaardt en als retourwaarde een lijst geeft met de drie gegevens over de puntlading (lading, de x-coordinaat en de y-coordinaat).

**Voorbeeld:**
Binnen jouw functie plaats je een puntlading van 1 C op de plaats (1.0 , 1.5) binnen het assenstelsel. Bij het uitvoeren van jouw functie:
```python
# maak hier jouw functie puntlading() aan
print( "[lading,xcoo,ycoo] =",puntlading() )
```
is de uitvoer dan:
```
[lading,xcoo,ycoo] = [1, 1.0, 1.5]
```

> **TIP: Neem alvast een kijkje naar de volgende paragraaf 2.2, daar kun je jouw puntlading tekenen!**

<span style="color:#1569C7">**Opdracht 6.**</span> We breiden de vorige opdracht uit naar de functie `puntladingen()` die meerdere puntladingen op het xy assenstelsel kan plaatsen. Jouw functie aanvaardt geen argumenten en geeft als retourwaarde een lijst met daarin voor elke geplaatste puntlading een lijst met de drie gegevens over die puntlading (lading, de x-coordinaat en de y-coordinaat).

**Voorbeeld:**
Binnen jouw functie plaats je twee puntladingen in het xy assenstelsel:
- een puntlading van 1 C op de plaats (-1.0, 0.5)
- een puntlading van -1 C op de plaats (1.0, 0.0).

Bij het uitvoeren van jouw functie:
```python
# maak hier jouw functie puntladingen() aan
print( "Lijst met [lading,xcoo,ycoo] per puntlading :",puntladingen() )
```
is de uitvoer dan:
```
Lijst met [lading,xcoo,ycoo] per puntlading : [[1, -1, 0.5], [-1, 1, 0]]
```

<span style="color:#1569C7">**Opdracht 7.**</span> We breiden de vorige opdracht verder uit naar de functie `plaat()` die 50 puntladingen van telkens +0.02 C naast elkaar op het xy assenstelsel kan plaatsen zodat het resultaat lijkt op een geleidende vlakke plaat van +1 C. Zoals voorheen aanvaardt jouw functie geen argumenten en geeft het als retourwaarde een lijst met daarin voor elke geplaatste puntlading een lijst met de drie gegevens over die puntlading (lading, de x-coordinaat en de y-coordinaat).

**Voorbeeld:**
Binnen jouw functie plaats je 50 puntladingen op de y-as (x=0 voor elk van de puntladingen) tussen $y=-3$ en $y=3$, met gelijke afstand tussen elk van de puntladingen.
> TIP: Gebruik hiervoor een loop! 

Bij het uitvoeren van jouw functie:
```python
# maak hier jouw functie plaat() aan
print( "Lijst met [lading,xcoo,ycoo] per puntlading :",plaat() )
```
is de uitvoer dan:
```
Lijst met [lading,xcoo,ycoo] per puntlading op de plaat : [[0.02, 0, -3.0], [0.02, 0, -2.877551020408163], [0.02, 0, -2.7551020408163267], [0.02, 0, -2.63265306122449], [0.02, 0, -2.510204081632653], [0.02, 0, -2.387755102040816], [0.02, 0, -2.2653061224489797], [0.02, 0, -2.142857142857143], [0.02, 0, -2.020408163265306], [0.02, 0, -1.8979591836734695], [0.02, 0, -1.7755102040816326], [0.02, 0, -1.653061224489796], [0.02, 0, -1.5306122448979593], [0.02, 0, -1.4081632653061225], [0.02, 0, -1.2857142857142858], [0.02, 0, -1.163265306122449], [0.02, 0, -1.0408163265306123], [0.02, 0, -0.9183673469387754], [0.02, 0, -0.795918367346939], [0.02, 0, -0.6734693877551021], [0.02, 0, -0.5510204081632653], [0.02, 0, -0.4285714285714288], [0.02, 0, -0.30612244897959195], [0.02, 0, -0.18367346938775508], [0.02, 0, -0.06122448979591866], [0.02, 0, 0.06122448979591821], [0.02, 0, 0.18367346938775508], [0.02, 0, 0.30612244897959195], [0.02, 0, 0.4285714285714284], [0.02, 0, 0.5510204081632653], [0.02, 0, 0.6734693877551021], [0.02, 0, 0.7959183673469385], [0.02, 0, 0.9183673469387754], [0.02, 0, 1.0408163265306118], [0.02, 0, 1.1632653061224492], [0.02, 0, 1.2857142857142856], [0.02, 0, 1.408163265306122], [0.02, 0, 1.5306122448979593], [0.02, 0, 1.6530612244897958], [0.02, 0, 1.7755102040816322], [0.02, 0, 1.8979591836734695], [0.02, 0, 2.020408163265306], [0.02, 0, 2.1428571428571423], [0.02, 0, 2.2653061224489797], [0.02, 0, 2.387755102040816], [0.02, 0, 2.5102040816326525], [0.02, 0, 2.63265306122449], [0.02, 0, 2.7551020408163263], [0.02, 0, 2.8775510204081627], [0.02, 0, 3.0]]
```

### 2.2. Teken de puntlading(en) op een figuur

Nu gaan we de puntlading(en) op een assenstelsel plaatsen. De code hieronder zal - mits succesvolle voltooiing van **Opdracht 5** de puntlading weergeven. Uitvoeren maar...
- Blijkt de code hieronder niet te werken? Bekijk opdracht 5 opnieuw in detail en controleer als jouw functie _exact_ dezelfde oplossing geeft als het voorbeeld, dat is écht nodig!
- Krijg je de figuur? Schitterend. Bestudeer dan aandachtig de code. Je zult die in de opdrachten hieronder aanpassen zodat het ook werkt voor meerdere puntladingen.

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
plt.style.use('dark_background')

#====================================#
#=== OPROEP LOCATIES PUNTLADINGEN ===#
#=== VOER EERST JOUW FUNCTIE UIT! ===#
#====================================#

charge = puntlading()
print( "[lading,xcoo,ycoo] =",charge )

# figuur settings
WIDTH  = 700
HEIGHT = 700
DPI    = 100


#==============#
#=== FIGUUR ===#
#==============#

fig = plt.figure(figsize=(WIDTH/DPI, HEIGHT/DPI))
ax  = fig.add_subplot()
fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

# Plaats de puntlading (charge in het engels) als een cirkel in het assenstelsel
q,xco,yco = charge
if q>0:
    ax.add_artist(Circle([xco,yco], 0.05, color='tab:red', zorder=10))
else:
    ax.add_artist(Circle([xco,yco], 0.05, color='tab:blue', zorder=10))

ax.set_xlim(-5,5)
ax.set_ylim(-5,5)
ax.set_aspect('equal')
plt.show()

<span style="color:#1569C7">**Opdracht 8.**</span> Hieronder vind je een kopie van de code hierboven, met één verschil: ik riep jouw functie `puntladingen()` aan om twee puntladingen in het assenstelsel te tekenen. Echter, je zult zien dat het uitvoeren van deze code leidt tot een foutmelding:
> **ValueError**: not enough values to unpack (expected 3, got 2)

Verbeter de code zodat alle puntladingen die je in jouw functie `puntladingen()` aanmaakte worden getoond. Zorg ervoor dat jouw code _veralgemeenbaar_ is. In dit geval betekent dit dat je op regel 10 ook perfect `plaat()` moet kunnen oproepen, zonder verdere aanpassingen in jouw code! In het laatste geval krijg je inderdaad een rode 'plaat' (50 rode stippen onder elkaar) te zien op de figuur!

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
plt.style.use('dark_background')

#====================================#
#=== OPROEP LOCATIES PUNTLADINGEN ===#
#=== VOER EERST JOUW FUNCTIE UIT! ===#
#====================================#

charges = puntladingen()
print( "Lijst met [lading,xcoo,ycoo] per puntlading :",charges )

# figuur settings
WIDTH  = 700
HEIGHT = 700
DPI    = 100


#==============#
#=== FIGUUR ===#
#==============#

fig = plt.figure(figsize=(WIDTH/DPI, HEIGHT/DPI))
ax  = fig.add_subplot()
fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

# Plaats de puntladingen (charges in het engels) als cirkels in het assenstelsel
q,xco,yco = charges
if q>0:
    ax.add_artist(Circle([xco,yco], 0.05, color='tab:red', zorder=10))
else:
    ax.add_artist(Circle([xco,yco], 0.05, color='tab:blue', zorder=10))

ax.set_xlim(-5,5)
ax.set_ylim(-5,5)
ax.set_aspect('equal')
plt.show()

## 3. Voorstelling van de elektrische veldlijnen rond de lading(en)

In deel 1 bestudeerden we de veldsterkte in **één punt** ($x_P$,$y_P$). Om een elektrisch veld te tekenen is dit echter onvoldoende. Theoretisch gezien is een elektrisch veld namelijk een voorstelling van de elektrische veldsterkte in **élk punt** van de ruimte. Onze computer kan veel - heel veel, maar de veldsterkte in een oneindig aantal punten berekenen, is van het goede te veel. Het doel van dit derde deel is om de veldsterkte te bepalen in **voldoende punten** om een realistische weergave van het elektrisch veld te bekomen.

### 3.1. Verdeling van het assenstelsel in een 'grid'

Als voorbeeld nemen we het assenstelsel dat we hierboven al visualiseerden. Terwijl je de code of de figuur zelf bestudeerde, viel het je misschien op dat we zowel de x-as als de y-as beperkten tot het interval [-5,5]. Binnen die grenzen maken we nu een 6x6 grid zoals hieronder getekend. Tel gerust even na, in totaal telt dit grid 36 hoek- of snijpunten.

<img src='https://cdn.images.fecom-media.com/FE00002114/images/B8R01922_H47968-PHE-CHE-I50_c8IKLcGz7E.jpg?width=578&height=578&scale=UpscaleCanvas&anchor=MiddleCenter' width='20%'>

Onderstaande functie `grid(nx,ny)` maakt dit grid in python als _nx_=_ny_=6. De functie heeft twee retourwaardes (_X_ en _Y_): de eerste retourwaarde (_X_) bevat 6x6 waardes die de _x_-coordinaten van elk punt van het grid voorstellen; de tweede retourwaarde (_Y_) bevat eveneens 6x6 waardes met alle _y_-coordinaten.

> **BELANGRIJK**: Binnen de lessen wiskunde zul je later dit jaar zo'n geordende tabel getallen de naam **MATRIX** geven. Zowel _X_ als _Y_ zijn voorbeelden van _6x6_ matrices (meervoud van matrix). De notatie _6x6_ betekent dat de getallen in 6 rijen en 6 kolommen zijn geordend.

In [ ]:
import numpy as np

def grid(nx,ny):
    # nx # aantal punten volgens de x-as
    # ny # aantal punten volgens de y-as
    x = np.linspace(-5, 5, nx) # deel de x-as op in nx gelijke stukken binnen de grenzen [-5,5]
    y = np.linspace(-5, 5, ny) # deel de y-as op in ny gelijke stukken binnen de grenzen [-5,5]
    X, Y = np.meshgrid(x, y) # combinatie van de gewenste opsplitsing van de x-as én y-as
    return X,Y

<span style="color:#1569C7">**Opdracht 9.**</span> In deze opdracht bekijken we de retourwaardes van de `grid(nx,ny)` functie even naderbij. Stel _nx_=6 en _ny_=6. Schrijf een programma dat beide geretourneerde matrices print:
- eerst de 6x6 matrix met alle x-coordinaten
- daarna de 6x6 matrix met alle y-coordinaten

**Opmerkingen:**
> - Roep hiervoor natuurlijk de functie `grid(nx,ny)` op.
> - Let er op dat zelfs de lay-out van de uitvoer identiek is aan het onderstaande voorbeeld!
> - Witregels kun je invoegen met een 'lege' `print()`.
<!-- Bestudeer de stukken code hierboven kunnen je zeker helpen om de dubbele retourwaarde van de `grid()` functie te verwerken! -->

**Voorbeeld:**
Jouw programma moet _exact_ volgende uitvoer geven:
```
Alle x-coordinaten van het grid zijn:
[[-5. -3. -1.  1.  3.  5.]
 [-5. -3. -1.  1.  3.  5.]
 [-5. -3. -1.  1.  3.  5.]
 [-5. -3. -1.  1.  3.  5.]
 [-5. -3. -1.  1.  3.  5.]
 [-5. -3. -1.  1.  3.  5.]]

Alle y-coordinaten van het grid zijn:
[[-5. -5. -5. -5. -5. -5.]
 [-3. -3. -3. -3. -3. -3.]
 [-1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 3.  3.  3.  3.  3.  3.]
 [ 5.  5.  5.  5.  5.  5.]]
```

### 3.2. Elektrische veldsterkte op elk gridpunt omwille van één puntlading

We hebben drie belangrijke stappen gezet:
- Binnen onze functie `puntlading()` bepalen we de lading _q_ van de puntlading en de positie (_xQ_,_yQ_) op het assenstelsel.
- Daarnaast plaatst onze `grid(nx,ny)` functie een veelheid aan punten als een grid op het assenstelsel.
- Op elk hoek- en snijpunt van dat grid willen we nu de elektrische veldsterkte bepalen. Hiervoor maken we gebruik van de `Exycomponenten(q, xQ, yQ, xP, yP)` functie, dewelke ons de $E_x$ en $E_y$ componenten van de elektrische veldsterkte geeft **op elk van de gridpunten**.

> **BELANGRIJK**: Als je nu goed hebt opgelet, zag je dat de variabelen _xP_ en _yP_ niet langer _integers_ zijn, maar wel _matrices_ die elk 36 getallen bevatten. Nu heb ik fantastisch nieuws voor jou: jouw functie `Exycomponenten(q, xQ, yQ, xP, yP)` die je maakte in deel 1 van dit project, werkt met matrices _xP_ en _yP_ even goed als het voorheen werkte met de integers _xP_ en _yP_. Omdat je in de lessen wiskunde nog niet leerde rekenen met matrices, ga ik niet dieper in op het 'waarom'.
> 
> In de plaats volstaat het te aanvaarden dat:
> - als _xP_ en _yP_ _integers_ zijn, dan berekent jouw functie `Exycomponenten(q, xQ, yQ, xP, yP)` de elektrische veldsterkte in één punt (_xP_,_yP_);
> - als _xP_ en _yP_ _matrices_ zijn, dan berekent jouw functie `Exycomponenten(q, xQ, yQ, xP, yP)` de elektrische veldsterkte op alle punten tegelijkertijd (in bovenstaand voorbeeld zijn dat 36 punten ineens)!

Laat ons nu elk van die drie stappen gestructureerd na elkaar uitvoeren in een nieuwe functie `EGRID(nx,ny)` waarbij _nx_ en _ny_ nog steeds het aantal punten van het grid betekenen.

In [ ]:
def EGRID(nx,ny):
    #==========================================================#
    #===   BEPAAL DE LADING EN POSITIE VAN DE PUNTLADING    ===#
    #==========================================================#
    charge    = puntlading()
    q, xQ, yQ = charge # [q]=Coulomb , xQ en yQ zijn de coordinaten van de lading op het assenstelsel
    
    #==========================================================#
    #===                   MAAK HET GRID                    ===#
    #==========================================================#
    xP, yP    = grid(nx,ny) # coordinaten van de punten waar we de elektrische veldsterkte wensen te bepalen
    
    #==========================================================#
    #=== BEREKEN DE ELEKTRISCHE VELDSTERKTE OP ELK GRIDPUNT ===#
    #==========================================================#
    Ex, Ey    = Exycomponenten(q, xQ, yQ, xP, yP)
    return Ex,Ey

<span style="color:#1569C7">**Opdracht 10.**</span> In deze opdracht bekijken we de retourwaardes van de `EGRID(nx,ny)` functie even naderbij. Stel _nx_=2 en _ny_=2 zodat de functie de elektrische veldsterkte berekent op vier gridpunten. Schrijf een programma dat beide geretourneerde matrices print:
- eerst de 2x2 matrix met alle x-coordinaten $E_x$
- daarna de 2x2 matrix met alle y-coordinaten $E_y$.

**Opmerkingen:**
> - Roep hiervoor natuurlijk de functie `EGRID(nx,ny)` op.
> - Let er op dat zelfs de lay-out van de uitvoer identiek is aan het onderstaande voorbeeld!
<!-- Bestudeer de stukken code hierboven kunnen je zeker helpen om de dubbele retourwaarde van de `grid()` functie te verwerken! -->

**Voorbeeld:**
Jouw programma moet _exact_ volgende uitvoer geven:
```
Alle x-coordinaten van de elektrische veldsterkte (Ex) zijn:
[[-7.79263658e+07  8.08864525e+07]
 [-1.60940359e+08  2.39492548e+08]]

Alle y-coordinaten van de elektrische veldsterkte (Ey) zijn:
[[-8.44202296e+07 -1.31440485e+08]
 [ 9.38818761e+07  2.09555980e+08]]
```

Nu we in staat zijn om de elektrische veldsterkte te berekenen op elk snijpunt van een gekozen grid, rest ons enkel nog te tekenen. Hiervoor maken we gebruik van heel wat functies beschikbaar in de `matplotlib.pyplot` module. Hieronder vind je de code die een "streamline" figuur produceert. Bestudeer elk stuk van deze code goed!

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
plt.style.use('dark_background')
import numpy as np

#============================================#
#=== BEREKEN E VOOR ELK PUNT VAN HET GRID ===#
#============================================#
# Voor een goede figuur zorgen we voor voldoende gridpunten (60x60 volstaat)
nx = 60
ny = 60
Ex,Ey = EGRID(nx,ny)


# figuur settings
WIDTH  = 700
HEIGHT = 700
DPI    = 100


#==============#
#=== FIGUUR ===#
#==============#

fig = plt.figure(figsize=(WIDTH/DPI, HEIGHT/DPI))
ax  = fig.add_subplot()
fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

# Plaats de puntlading (charge in het engels) als een cirkel in het assenstelsel
charge    = puntlading()
q, xQ, yQ = charge        # [q]=Coulomb , xQ en yQ zijn de coordinaten van de lading op het assenstelsel
if q>0:
    ax.add_artist(Circle([xQ,yQ], 0.05, color='tab:red', zorder=10))
else:
    ax.add_artist(Circle([xQ,yQ], 0.05, color='tab:blue', zorder=10))

# Maak een veldlijnen voorstelling met behulp van de Ex en Ey componenten
color = np.log(np.sqrt(Ex**2 + Ey**2))
ax.streamplot(np.linspace(-5, 5, nx), np.linspace(-5, 5, ny), Ex, Ey, color=color, linewidth=1, cmap=plt.cm.plasma, density=3, arrowstyle='->')

ax.set_xlim(-5,5)
ax.set_ylim(-5,5)
ax.set_aspect('equal')
plt.show()

### 3.3. Elektrische veldsterkte op elk gridpunt omwille van meerdere puntladingen

Zo, nu is het aan jou! Je hebt alle benodigdheden om de veldlijnen te tekenen rondom meerdere puntladingen. Ik help je even op weg met de te volgen stappen:
- Gebruik jouw functie `puntladingen()` of `plaat()` of elke andere functie die ladingen _q_ en hun locaties beschrijft;
- Maak een grid aan met de functie `grid(nx,ny)` en specifiëer op hoeveel gridpunten de elektrische veldsterkte zal worden berekend;
- Bereken de componenten van de elektrische veldsterkte $E_x$ en $E_y$ met de functie `Exycomponenten(q, xQ, yQ, xP, yP)`.

> **LET OP:**
> In de laatste stap schuilt een belangrijke adder. De functie `Exycomponenten(q, xQ, yQ, xP, yP)` kan slechts worden opgeroepen voor één enkele puntlading. Je zult de functie dus achtereenvolgens voor elk van de individuele puntladingen moeten oproepen! Ruik je ook die _loop_?

Nog één opmerking voor je begint. Om de totale elektrische veldsterkte te weten in een punt omwille van verschillende puntladingen, mag je de componenten eenvoudigweg optellen. Bekijk als voorbeeld de figuur hieronder. Stel dat een punt (hier de oorsprong) een veldsterkte $\vec{E_1}$ ondervindt omwille van een eerste puntlading en daarenboven een veldsterkte $\vec{E_2}$ ondervindt omwille van een tweede puntlading, dan is de totale veldsterkte in dat punt de vectorsom $\vec{E} = \vec{E_1} + \vec{E_2}$. Componentgewijs betekent dit:
$$
\begin{cases}
E_x = E_{1x} + E_{2x} \\
E_y = E_{1y} + E_{2y}
\end{cases}
$$

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_vectorsom.png?raw=true' width='50%'>


<span style="color:#1569C7">**Opdracht 11.**</span> Schrijf een programma dat een "streamline" figuur produceert in de aanwezigheid van meerdere puntladingen. Roep hiervoor jouw functie `puntladingen()` op.

> **Tip:** Baseer je voor de figuur uiteraard op de bovenstaande code voor één puntlading.

Jouw code geeft als resultaat:

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_punladingen.png?raw=true' width='50%'>

<span style="color:#1569C7">**Opdracht 12.**</span> Schrijf een programma dat een "streamline" figuur produceert in de aanwezigheid van meerdere puntladingen die samen een quasi-continue ladingsverdeling vormen. Kies zelf een ladingsverdeling. Als voorbeeld toon ik hieronder het elektrisch veld rondom twee parallelle platen.

<img src='https://github.com/jonasvdw/IW_Teams/blob/main/media/P5_project2_parallelplaten.png?raw=true' width='50%'>